<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<script type="text/x-magento-init">
{
    ".wp-block-kadence-tabs": {
        "Mooore_WordpressIntegrationCms/js/kadence-blocks/tabs": {}
    },
    ".kt-blocks-carousel": {
        "Mooore_WordpressIntegrationCms/js/kadence-blocks/advanced-gallery/slider": {}
    },
    ".frm_forms": {
        "Mooore_WordpressIntegrationCms/js/formidable-blocks/index": {}
    }
}
</script>
