<?php
namespace Mooore\WordpressIntegrationCms\Cron;

use Mooore\WordpressIntegrationCms\Model\RemotePostRepository;
use Mooore\WordpressIntegration\Api\SiteRepositoryInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use Magento\UrlRewrite\Model\UrlPersistInterface;

class IndexBlogUrls {
    const URLREWRITE_ENTITY_TYPE = 'wpci-blog-post';

    /**
     * @var RemotePostRepository
     */
    protected $remotePostRepository;

    /**
     * @var SiteRepositoryInterface
     */
    protected $siteRepository;

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var UrlPersistInterface
     */
    protected $urlPersistInterface;

    public function __construct(
        RemotePostRepository $remotePostRepository,
        SiteRepositoryInterface $siteRepository,
        UrlRewriteFactory $urlRewriteFactory,
        UrlPersistInterface $urlPersistInterface
    ) {
        $this->remotePostRepository = $remotePostRepository;
        $this->siteRepository = $siteRepository;
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->urlPersistInterface = $urlPersistInterface;
    }

    public function execute() {
        $sites = $this->remotePostRepository->getList();

        $rewrites = [];

        foreach ($sites as $siteId => $site) {
            $site_opts = $this->siteRepository->get($siteId);

            if (!$site_opts->getEnableBlog()) {
                continue;
            }

            $prefix = $site_opts->getBlogPrefix() ?? '';
            $prefix = ltrim($prefix, '/'); // Remove trailing slash
            $blogStores = explode(',', $site_opts->getBlogStores());

            foreach ($site['data'] as $post) {
                $postId = $post['id'];
                $slug = $post['slug'];

                foreach ($blogStores as $blogStoreId) {
                    $rewrites[] = $this->urlRewriteFactory->create()
                        ->setStoreId($blogStoreId)
                        ->setEntityType(self::URLREWRITE_ENTITY_TYPE)
                        ->setEntityId($siteId . "0" . $postId)
                        ->setRequestPath("$prefix/$slug")
                        ->setTargetPath("wpci/blog/view/site_id/$siteId/page_id/$postId")
                        ->setIsAutogenerated(1)
                        ->setDescription("Generated by WPCI Blogs. Edit this in Content > Sites")
                        ->setRedirectType(0);
                }
            }
        }

        $this->urlPersistInterface->replace($rewrites);
    }
}
